### ISSUE TITLE
object '[Data Included]' not found

### ISSUE THREAD

**Issue by jaredraynes** [nguyens7/tidyNano#3]
Hi there, thanks for writing the package. 

I installed and followed your instructions, trying the example first which imports the data like it should. When I go to import my own data i get the following error:

> data.file <- "~/Caseinate_NTA/Caseinates_Nanosight/A1A1/A1_35.csv"
> data <- nanoimport(data.file)
NTA version: 3
Sample name: Sample 35 caseinates 1500x dil
Error in .f(.x[[i]], ...) : object '[Data Included]' not found

I checked my file and it looks exactly like your example file, and the [Data Included] line is 
my file. Help!

I attach my file as a .txt so I could upload it. Just change it back to .csv to use.

[A1_35 - Copy.txt](https://github.com/nguyens7/tidyNano/files/3796609/A1_35.-.Copy.txt)

**Comment by jaredraynes** [comment]
Opening your beads.csv example in Notepad shows that there are a lot more commars so this may be my problem. But My file is how it is saved off my machine.. E.g the [Data included] isn't wrapped by commars.

**Comment by nguyens7** [comment]
Thanks for submitting an issue,  I think the problem is because` nanoimport()` was written to accommodate NTA software  v2.3, 3.1, and 3.2  since those were the versions I could get my hands on to create protoype/beta test tidyNano.  Looks like I can try to fix the `nanoimport()` function to import NTA v3.0 within the next couple days.

**Comment by jaredraynes** [comment]
Thanks for your prompt responce. I can also see if I can save it through software V3.2 and if that changes the commars.

**Comment by nguyens7** [comment]
I've updated `nanoimport()` to be more robust and it should be able to automatically import your data now.  Just install the new version (0.1.2) of tidyNano and it should fix the problem.  See if the following code works for you.  The `custom_name` argument is to account for your sample dilution. I also updated the README.md to highlight some suggestions for naming samples to make it easier to process with tidyNano in the future.

`nanoimport("A1_35.-.Copy.csv", auto_name = TRUE, custom_name = "1500") %>%
  nanotidy(sep_var = c("Tech_rep", "Dilution", "Sample")) %>% 
  ggplot(aes(x = particle_size, y = True_count, color = Tech_rep )) +
  geom_line()`

<img width="818" alt="Screen Shot 2019-11-01 at 5 11 42 PM" src="https://user-images.githubusercontent.com/18275928/68056899-b2827c00-fcca-11e9-8fb5-83ece1cad27e.png">

Hope this helps!

**Comment by nguyens7** [comment]
@jaredraynes, did the new update allow you to import the data?

**Comment by jaredraynes** [comment]
@nguyens7 yes that update worked, thank you! I am also thinking about whether the addition of a function to calculate total surface area and volume would be a good addition? This was originally available in software version 2.1 before the instrument and software were purchased by Malvern.

**Comment by nguyens7** [comment]
Great, I'm glad that it's working for you!   I'll create another issue to see if I can work on a way to import and calculate the surface area and volume data.
