### ISSUE TITLE
Nanocombine not working in conjuction with Nanotidy()

### ISSUE THREAD

**Issue by soohyuna** [nguyens7/tidyNano#6]
Error: Names must be unique. x These names are duplicated: * "particle_size" at locations 91, 122, and 243. Run `rlang::last_error()` to see where the error occurred.

I am attempting to combine multiple csv files exported from the nanosight. When I add use the nanocombine function, all the data is merged into one DF, but it pulls particle size from each csv resulting in redundant columns names. I believe this is incompatible with the subsequent nanotidy function.

**Comment by nguyens7** [comment]
Fixed the nanocombine function with the latest commit!
